package com.atguigu.gmall0826.realtime.bean

case class OrderInfo(
                      id: String,
                      province_id: String,
                      consignee: String,
                      order_comment: String,
                      var consignee_tel: String,
                      order_status: String,
                      payment_way: String,
                      user_id: String,
                      img_url: String,
                      total_amount: Double,
                      expire_time: String,
                      delivery_address: String,
                      create_time: String,
                      operate_time: String,
                      tracking_no: String,
                      parent_order_id: String,
                      out_trade_no: String,
                      trade_body: String,
                      var create_date: String,
                      var create_hour: String,
                      a: String,
                      b: String,
                      c: String,
                      d: String,
                      var e: String,
                      var f: String,
                      g: String,
                      h: String,
                      i: String,
                      j: String,
                      var k: String,
                      var l: String,
                      m: String,
                      n: String,
                      o: String,
                      p: String,
                      var q: String,
                      var r: String,
                      s: String,
                      t: String,
                      u: String,
                      v: String,
                      var w: String,
                      var x: String 
                    )

